# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='pokers',
            field=models.ManyToManyField(related_name='_user_pokers_+', to='login_app.User'),
        ),
    ]
