# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20180424_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
